### ISSUE TITLE
모든 코드를 직접 만드셨나요?

### ISSUE THREAD

**Issue by Akaza-Akari** [Ganggroid/KKuTu-co-kr#2]
![image](https://cloud.githubusercontent.com/assets/21969938/24828589/2dca0d3c-1c9b-11e7-8d17-7a9e14b7999d.png)
https://github.com/JJoriping/KKuTu 가 원본인걸로 아는데 왜 구지 포크하지 않으시고 개별 레포를 만들어서 기록에 본인만 나오시게 한건지 의문이 듭니다.

**Comment by Ganggroid** [comment]
fork를 잘 활용할 줄 몰라서 fork 하지 않고 개별 레포지토리를 새로 생성하였습니다.
